# Generated by Django 3.2.6 on 2021-09-02 08:50

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField()),
                ('mod_date', models.DateTimeField()),
                ('name', models.CharField(default='Default category', max_length=30, unique=True)),
                ('author', models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-mod_date'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField()),
                ('mod_date', models.DateTimeField()),
                ('title', models.TextField(default='Default title', max_length=30, verbose_name='Title')),
                ('version_no', models.IntegerField(blank=True, default=1, verbose_name='Version No.')),
                ('docfile', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d')),
                ('author', models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='documents.category')),
            ],
            options={
                'ordering': ['-mod_date'],
            },
        ),
    ]
